export const REQUEST_DATA = "POST/REQUEST_DATA";
export const FETCH_POSTS = "POST/FETCH_POSTS";
export const FETCH_USERS = "POST/FETCH_USERS";
export const FILTER_BY_AUTHOR = "POST/FILTER_BY_AUTHOR";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";
